# Documentation
# https://github.com/bbatsov/rubocop/blob/master/config/default.yml
# http://rubocop.readthedocs.io/en/latest

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

Documentation:
  Enabled: false

LineLength:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'config/initializers/secure_headers.rb'
    - 'node_modules/**/*'

Bundler/OrderedGems:
  Enabled: false

Capybara/FeatureMethods:
  Enabled: false

Layout/AlignHash:
  Enabled: false

Layout/AlignParameters:
  Enabled: false

Layout/CaseIndentation:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false
  AllowForAlignment: true

Layout/IndentFirstArgument:
  Enabled: false

Layout/IndentFirstArrayElement:
  Enabled: false

Layout/IndentFirstHashElement:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Layout/MultilineBlockLayout:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Layout/SpaceInLambdaLiteral:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/AbcSize:
  # The ABC size is a calculated magnitude, so this number can be a Fixnum or a Float.
  Max: 240

Metrics/BlockLength:
  Max: 90

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  CountComments: false  # count full line comments?
  Max: 600

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 120

Metrics/PerceivedComplexity:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Rails/DynamicFindBy:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/UnknownEnv:
  Enabled: false

Rails/Validation:
  Enabled: false

RSpec/ExampleLength:
  Max: 15

RSpec/ImplicitExpect:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 10

RSpec/NestedGroups:
  Max: 4

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/ColonMethodCall:
  Enabled: false

Style/CommandLiteral:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/RedundantReturn:
  Enabled: false
  AllowMultipleReturnValues: true

Style/RedundantSelf:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/SymbolArray:
  Enabled: false
