development:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DATABASE_DEV_NAME'] %>
  host: localhost
  pool: 15
  username: <%= ENV['DATABASE_DEV_USERNAME'] %>
  password: <%= ENV['DATABASE_DEV_PASSWORD'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DATABASE_TEST_NAME'] %>
  host: localhost
  pool: 15
  username: <%= ENV['DATABASE_TEST_USERNAME'] %>
  password: <%= ENV['DATABASE_TEST_PASSWORD'] %>

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DATABASE_PROD_DBNAME'] %>
  host: localhost
  pool: 15
  connect_timeout: 30
  variables:
    statement_timeout: 15000
  username: <%= ENV['DATABASE_PROD_USERNAME'] %>
  password: <%= ENV['DATABASE_PROD_PASSWORD'] %>
