---
translations:
- file: 'public/assets/translations/default-:locale.json'
  patterns: ['*.js.helpers.*', '*.js.cookies.*', '*.js.no_cookies.*', '*.js.views.home.*', '*.js.views.header.*', '*.js.views.sidebar.*', '*.js.views.footer.*', '*.js.topic.*', '*.js.inventory_fields.*', '*.js.article.*', '*.js.tag.*', '*.js.user.*', '*.js.search.*', '*.js.comment.*', '*.js.bookmark.*', '*.js.checkbox.*', '*.js.languages.*']

- file: 'public/assets/translations/user-:locale.json'
  patterns: ['*.js.helpers.*', '*.js.cookies.*', '*.js.no_cookies.*', '*.js.views.home.*', '*.js.views.header.*', '*.js.views.sidebar.*', '*.js.views.footer.*', '*.js.topic.*', '*.js.inventory_fields.*', '*.js.article.*', '*.js.tag.*', '*.js.user.*', '*.js.search.*', '*.js.editor.*', '*.js.comment.*', '*.js.bookmark.*', '*.js.checkbox.*', '*.js.languages.*', '*.js.selecter.*']

- file: 'public/assets/translations/admin-:locale.json'
  patterns: ['*.js.helpers.*', '*.js.topic.*', '*.js.inventory_fields.*', '*.js.article.*', '*.js.tag.*', '*.js.user.*', '*.js.search.*', '*.js.editor.*', '*.js.comment.*', '*.js.bookmark.*', '*.js.checkbox.*', '*.js.languages.*', '*.js.selecter.*', '*.js.admin.*']
